# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 31495a31cb81bdaca1bb6f285d67e9829ee03eed497958350a0ee00a7465ac7a66c766c9f7d56e4185fadd203f8033e5792e5475a1a763a8cd8ccdd79e31877b

test:
  secret_key_base: 6c24ea49952d8c35a23196a55c6a1b86fa623b27243e48a275db47e5fab182166df4a9d19b196dbf7dff02c48b165c06ff8c359d342f6d6d76504be975bb860d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
